friendly message

diff --git a/alpine/assets/share/mysql/service b/alpine/assets/share/mysql/service
--- a/alpine/assets/share/mysql/service
+++ b/alpine/assets/share/mysql/service
@@ -13,13 +13,13 @@ app_start() {
 
 app_stop() {
 
-    kill -TERM `cat ${APP_PID_FILE}`
+    kill -TERM `cat $APP_PID_FILE`
 
 }
 
 app_reload() {
 
-    kill -HUP `cat ${APP_PID_FILE}`
+    kill -HUP `cat $APP_PID_FILE`
 
 }
 
@@ -40,13 +40,21 @@ app_helper() {
 
 }
 
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ mysql \033[32mdone \033[0m"
+    else
+        echo -e "$@ mysql \033[31mfailed \033[0m"
+    fi
+
+}
+
 #####################################################################
 
 app_helper $1
 
-echo "${1} mysql ..."
-app_${@}
+echo "$1 mysql ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} mysql failed"
-fi
+app_$1
+app_result $1
diff --git a/alpine/assets/share/nginx/service b/alpine/assets/share/nginx/service
--- a/alpine/assets/share/nginx/service
+++ b/alpine/assets/share/nginx/service
@@ -34,8 +34,18 @@ app_helper() {
     local DOES="start|stop|reload|restart"
 
     if ! echo "|$DOES|" | grep -q "|$1|"; then
-        echo "Usage: nginx mysql {$DOES}"
+        echo "Usage: webox nginx {$DOES}"
         exit 1
+    fi
+
+}
+
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ nginx \033[32mdone \033[0m"
+    else
+        echo -e "$@ nginx \033[31mfailed \033[0m"
     fi
 
 }
@@ -44,9 +54,7 @@ app_helper() {
 
 app_helper $1
 
-echo "${1} nginx ..."
-app_${@}
+echo "$1 nginx ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} nginx failed"
-fi
+app_$1
+app_result $1
diff --git a/alpine/assets/share/php7/service b/alpine/assets/share/php7/service
--- a/alpine/assets/share/php7/service
+++ b/alpine/assets/share/php7/service
@@ -41,13 +41,13 @@ app_start() {
 
 app_stop() {
 
-    kill -TERM `cat ${APP_PID_FILE}`
+    kill -TERM `cat $APP_PID_FILE`
 
 }
 
 app_reload() {
 
-    kill -USR2 `cat ${APP_PID_FILE}`
+    kill -USR2 `cat $APP_PID_FILE`
 
 }
 
@@ -68,13 +68,21 @@ app_helper() {
 
 }
 
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ php7 \033[32mdone \033[0m"
+    else
+        echo -e "$@ php7 \033[31mfailed \033[0m"
+    fi
+
+}
+
 #####################################################################
 
 app_helper $1
 
-echo "${1} php7 ..."
-app_${@}
+echo "$1 php7 ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} php7 failed"
-fi
+app_$1
+app_result $1
diff --git a/alpine/assets/share/postgresql/service b/alpine/assets/share/postgresql/service
--- a/alpine/assets/share/postgresql/service
+++ b/alpine/assets/share/postgresql/service
@@ -43,8 +43,18 @@ app_helper() {
     local DOES="start|stop|reload|restart"
 
     if ! echo "|$DOES|" | grep -q "|$1|"; then
-        echo "Usage: postgresql mysql {$DOES}"
+        echo "Usage: webox postgresql {$DOES}"
         exit 1
+    fi
+
+}
+
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ postgresql \033[32mdone \033[0m"
+    else
+        echo -e "$@ postgresql \033[31mfailed \033[0m"
     fi
 
 }
@@ -53,9 +63,7 @@ app_helper() {
 
 app_helper $1
 
-echo "${1} postgresql ..."
-app_${@}
+echo "$1 postgresql ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} postgresql failed"
-fi
+app_$1
+app_result $1
diff --git a/alpine/assets/share/redis/service b/alpine/assets/share/redis/service
--- a/alpine/assets/share/redis/service
+++ b/alpine/assets/share/redis/service
@@ -15,13 +15,13 @@ app_start() {
 
 app_stop() {
 
-    kill -TERM `cat ${APP_PID_FILE}`
+    kill -TERM `cat $APP_PID_FILE`
 
 }
 
 app_reload() {
 
-    kill -HUP `cat ${APP_PID_FILE}`
+    kill -HUP `cat $APP_PID_FILE`
 
 }
 
@@ -36,8 +36,18 @@ app_helper() {
     local DOES="start|stop|reload|restart"
 
     if ! echo "|$DOES|" | grep -q "|$1|"; then
-        echo "Usage: redis mysql {$DOES}"
+        echo "Usage: webox redis {$DOES}"
         exit 1
+    fi
+
+}
+
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ redis \033[32mdone \033[0m"
+    else
+        echo -e "$@ redis \033[31mfailed \033[0m"
     fi
 
 }
@@ -46,9 +56,7 @@ app_helper() {
 
 app_helper $1
 
-echo "${1} redis ..."
-app_${@}
+echo "$1 redis ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} redis failed"
-fi
+app_$1
+app_result $1
diff --git a/alpine/assets/share/sshd/service b/alpine/assets/share/sshd/service
--- a/alpine/assets/share/sshd/service
+++ b/alpine/assets/share/sshd/service
@@ -13,13 +13,13 @@ app_start() {
 
 app_stop() {
 
-    kill -TERM `cat ${APP_PID_FILE}`
+    kill -TERM `cat $APP_PID_FILE`
 
 }
 
 app_reload() {
 
-    kill -HUP `cat ${APP_PID_FILE}`
+    kill -HUP `cat $APP_PID_FILE`
 
 }
 
@@ -34,8 +34,18 @@ app_helper() {
     local DOES="start|stop|reload|restart"
 
     if ! echo "|$DOES|" | grep -q "|$1|"; then
-        echo "Usage: webox ssh {$DOES}"
+        echo "Usage: webox sshd {$DOES}"
         exit 1
+    fi
+
+}
+
+app_result() {
+
+    if [ $? -eq 0 ]; then
+        echo -e "$@ sshd \033[32mdone \033[0m"
+    else
+        echo -e "$@ sshd \033[31mfailed \033[0m"
     fi
 
 }
@@ -44,9 +54,7 @@ app_helper() {
 
 app_helper $1
 
-echo "${1} sshd ..."
-app_${@}
+echo "$1 sshd ..."
 
-if [ ${?} -ne 0 ]; then
-    echo "${1} sshd failed"
-fi
+app_$1
+app_result $1
